### ISSUE TITLE
simba-awesome-js函数库无法下载

### ISSUE THREAD

**Issue by xiahuhu1** [dnsjia/devops#2]
`simba-awesome-js@1.0.6`这个js函数库貌似下载不了，有其他办法吗？
```
➜  devops-master npm install simba-awesome-js@1.0.6
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npm.taobao.org/simba-awesome-js
npm ERR! 404 
npm ERR! 404  'simba-awesome-js@1.0.6' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xiahuhu/.npm/_logs/2021-12-02T15_15_22_441Z-debug.log
```

**Comment by gujiwork** [comment]
先注释了试试

**Comment by gujiwork** [comment]
> `simba-awesome-js@1.0.6`这个js函数库貌似下载不了，有其他办法吗？
> 
> ```
> ➜  devops-master npm install simba-awesome-js@1.0.6
> npm ERR! code E404
> npm ERR! 404 Not Found - GET https://registry.npm.taobao.org/simba-awesome-js
> npm ERR! 404 
> npm ERR! 404  'simba-awesome-js@1.0.6' is not in the npm registry.
> npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
> npm ERR! 404 
> npm ERR! 404 Note that you can also install from a
> npm ERR! 404 tarball, folder, http url, or git url.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/xiahuhu/.npm/_logs/2021-12-02T15_15_22_441Z-debug.log
> ```

先注释了试试
