### ISSUE TITLE
打开界面提示无权限查看

### ISSUE THREAD

**Issue by gongjx11** [dnsjia/devops#4]
![image](https://user-images.githubusercontent.com/21954004/156142916-0ce74bf0-6acf-4666-81d6-96f7451a1463.png)

**Comment by gujiwork** [comment]
登录后台为用户绑定角色，角色分配权限和菜单，然后退出重新登录

**Comment by gujiwork** [comment]
> 登录后台为用户绑定角色，角色分配权限和菜单，然后退出重新登录



> ![图片](https://user-images.githubusercontent.com/21954004/156142916-0ce74bf0-6acf-4666-81d6-96f7451a1463.png)
